Aqarmap/Aqarmap/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin

from properties import urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^subscribtions/', include('subscribtions.urls', namespace='subscribtions')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^properties/', include('properties.urls', namespace='properties')),
    url(r'^listings/', include('listings.urls', namespace='listings')),
    url(r'^settings/', include('user_settings.urls', namespace='settings')),
    url(r'^', include('search.urls', namespace='search')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Aqarmap/properties/urls.py
from django.conf.urls import url
from . import views

app_name = 'properties'

urlpatterns = [
    url(r'^add/$', views.add_property, name='addproperty'),
    url(r'^forsale/$', views.prop_forSale, name='propertiesforsale'),
    url(r'^forrent/$', views.prop_forRent, name='propertiesforrent'),
    url(r'^all/$', views.list_u_prop, name='allproperties'),
    url(r'^(?P<property_id>[-0-9]+)/$',
        views.prop_details, name='properties_details'),
    # ex addProperty/5 - send <prop_id> as an arguments | [0-9]+ sequences of digits
    #url(r'^(?P<prop_id>[0-9]+)/$', views.details, name='prop_details'),
    #url(r'^(?P<addProperty_id>[0-9])/$', views.addProperty, name='add'),
]

Aqarmap/search/urls.py
from django.conf.urls import url

from . import views
app_name = 'search'
urlpatterns = [
    url(r'^$', views.main_search, name="index"),
    url(r'^results/', views.search_results, name="results"),
    url(r'^compare/(?P<first_prop>[0-9]+)/(?P<second_prop>[0-9]+)/$',
        views.property_compare, name="compare"),
]

Aqarmap/search/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

Aqarmap/search/forms.py
from django import forms
from properties.models import PROPERTIES_CATEGORIES, PROPERTIES_TYPES
from cities_light.models import City, Region
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Field
# from crispy_forms.bootstrap import StrictButton


class SearchForm(forms.Form):
    category = forms.ChoiceField(
        choices=PROPERTIES_CATEGORIES, widget=forms.Select(), required=False)
    city = forms.ModelChoiceField(
        queryset=Region.objects.all(), required=False)
    neighborhood = forms.ModelChoiceField(
        queryset=City.objects.all(), required=False)
    prop_type = forms.ChoiceField(
        choices=PROPERTIES_TYPES, widget=forms.Select(), required=False)
    minimum_price = forms.IntegerField(min_value=0, required=False)
    maximum_price = forms.IntegerField(min_value=0, required=False)

    def __init__(self, *args, **kwargs):
        super(SearchForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'search_form'
        self.helper.form_method = 'get'
        self.helper.form_action = 'results'
        self.helper.form_class = 'form-inline'
        self.helper.field_template = 'bootstrap3/layout/inline_field.html'
        self.helper.layout = Layout(
            Field('category',),
            Field('city'),
            Field('neighborhood'),
            Field('prop_type'),
            Field('minimum_price'),
            Field('maximum_price'),
        )
        self.helper.add_input(Submit('submit', 'Submit'))

Aqarmap/search/views.py
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from search.forms import SearchForm
from properties.models import Properties, PropertiesPhotos, PROPERTIES_TYPES
# Create your views here.


def main_search(request):
    form = SearchForm(request.GET or None)
    context = {
        "form": form,
    }
    return render(request, "search/main_search.html", context)


def search_results(request):
    if request.GET is not None:
        category = request.GET.get('category')
        city = request.GET.get('city')
        neighborhood = request.GET.get('neighborhood')
        prop_type = request.GET.get('prop_type')
        minimum_price = request.GET.get('minimum_price')
        maximum_price = request.GET.get('maximum_price')
        results = Properties.objects.filter(category=category, city=city or None,
                                            neighborhood=neighborhood or None, prop_type=prop_type or None,
                                            price__range=(minimum_price, maximum_price))

        # this will get all properties that have an image
        properties = PropertiesPhotos.objects.filter(
            prop__in=results).select_related('prop')
        paginator = Paginator(properties, 3)
        page = request.GET.get('page')
        try:
            props = paginator.page(page)
        except PageNotAnInteger:
            props = paginator.page(1)
        except EmptyPage:
            props = paginator.page(paginator.num_pages)
        sort = request.GET.get('sort', 'prop.created')
        context = {
            "results": props,
            "sort": sort,
        }
        return render(request, "search/results.html", context)


@login_required
def property_compare(request, first_prop, second_prop):
    results = Properties.objects.filter(Q(id=first_prop) | Q(id=second_prop))
    # this will get all properties that have an image
    properties = PropertiesPhotos.objects.filter(
        prop__in=results).select_related('prop')
    print(properties)
    context = {
        "results": properties,
    }
    return render(request, "search/compare.html", context)

Aqarmap/search/templates/search/compare.html
{% extends "base.html" %} {% load humanize %}{% load embed_video_tags %}{% block content %}
<div class="row">
    <h1>Properties Comparison</h1>
    {% for result in results %}
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <div class="thumbnail">
            <img src="{{ result.prop_photo.url }}" alt="">
            <div class="caption">
                <h2>{{ result.prop.title }} <small>{{ result.prop.created|naturaltime }}</small></h2>

                 <strong>Size :</strong> {{ result.prop.size }} M</small> <br> <strong>Price :</strong> {{ result.prop.price|intcomma }}<small> EGP</small></small><br>
                 <strong>City : </strong> {{ result.prop.city }}<br>
                 <strong>Neighborhood :</strong> {{ result.prop.neighborhood }}
                <hr>
                <strong>Description:</strong>
                <div class="well well-sm">
                    <p>
                        {{ result.prop.description}}
                    </p>
                </div>
                <strong>Youtube Video :</strong>
                <div class="well well-sm">
                    {% video result.prop.yt_url %}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

Aqarmap/search/templates/search/main_search.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% block content %}

    <h1>Search</h1>
    <hr>
{% crispy form %}

{% endblock content %}

Aqarmap/search/templates/search/results.html
{% extends "base.html" %} {% load humanize %} {% load staticfiles %}
{% block js %}
    <script src='{% static "search/js/results-utils.js" %}'></script>
{% endblock js %}
{% block content %}
<div class="row">
    <h1>Search Results</h1>
    <div>
        <strong>Sort By :</strong> <a href="{% url 'search:results' %}?category={{ request.GET.category }}&city={{ request.GET.city }}&neighborhood={{ request.GET.neighborhood }}&prop_type={{ request.GET.prop_type }}&minimum_price={{ request.GET.minimum_price }}&maximum_price={{ request.GET.maximum_price }}&sort=prop.size">Size</a> |
        <a href="{% url 'search:results' %}?category={{ request.GET.category }}&city={{ request.GET.city }}&neighborhood={{ request.GET.neighborhood }}&prop_type={{ request.GET.prop_type }}&minimum_price={{ request.GET.minimum_price }}&maximum_price={{ request.GET.maximum_price }}&sort=prop.price">Price</a> |
        <a href="{% url 'search:results' %}?category={{ request.GET.category }}&city={{ request.GET.city }}&neighborhood={{ request.GET.neighborhood }}&prop_type={{ request.GET.prop_type }}&minimum_price={{ request.GET.minimum_price }}&maximum_price={{ request.GET.maximum_price }}&sort=prop.modified">Creation</a>
    </div>
    <hr> {% for result in results|dictsort:sort %}
    <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
        <div class="thumbnail">
            <img src="{{ result.prop_photo.url }}" alt="">
            <div class="caption">
                <h2>{{ result.prop.title }} | <small>{{ result.prop.created|naturaltime }}</small></h2>
                <small>Type : {{ result.prop.prop_type }}</small> | <small> Size : {{ result.prop.size }}<small> M</small> | Price : {{ result.prop.price|intcomma }}<small> EGP</small></small>
                <hr>
                <div class="well well-sm">
                    <p>
                        {{ result.prop.description | truncatechars:100}}
                    </p>
                </div>
                <div>
                    <p>
                        <a href="{% url 'properties:properties_details' property_id=result.prop.id %}" class="btn btn-primary">Detail</a>
                        <a class="btn btn-default" name="compare" id="{{ result.prop.id }}">Compare</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<div class="pagination col-sm-12">
    <span class="step-links col-sm-offset-6">
        {% if results.has_previous %}
            <a href="?category={{ request.GET.category }}&city={{ request.GET.city }}&neighborhood={{ request.GET.neighborhood }}&prop_type={{ request.GET.prop_type }}&minimum_price={{ request.GET.minimum_price }}&maximum_price={{ request.GET.maximum_price }}&page={{ results.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ results.number }} of {{ results.paginator.num_pages }}
        </span> 
        {% if results.has_next %}
            <a href="?category={{ request.GET.category }}&city={{ request.GET.city }}&neighborhood={{ request.GET.neighborhood }}&prop_type={{ request.GET.prop_type }}&minimum_price={{ request.GET.minimum_price }}&maximum_price={{ request.GET.maximum_price }}&page={{ results.next_page_number }}">Next</a> {% endif %}
    </span>
</div>
{% endblock content %}