Aqarmap/Aqarmap/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin

from properties import urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^subscribtions/', include('subscribtions.urls', namespace='subscribtions')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^properties/', include('properties.urls', namespace='properties')),
    url(r'^listings/', include('listings.urls', namespace='listings')),
    url(r'^settings/', include('user_settings.urls', namespace='settings')),
    url(r'^', include('search.urls', namespace='search')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Aqarmap/listings/urls.py
from django.conf.urls import url
from . import views

app_name = 'listing'

urlpatterns = [

    url(r'^listProperties/$', views.listProperties, name='listProperties'),
    url(r'^editProperties/(?P<prop_id>[0-9]+)/$', views.EditProp, name='editproperty'),
    url(r'^deleteProperties/(?P<prop_id>[0-9]+)/$', views.delete, name='deleteProperty'),
    url(r'^activateProperties/(?P<prop_id>[0-9]+)/$', views.setActive, name='activeProperty'),
    url(r'^deactivateProperties/(?P<prop_id>[0-9]+)/$', views.setDeactive, name='deactiveProperty')

]

Aqarmap/search/urls.py
from django.conf.urls import url

from . import views
app_name = 'search'
urlpatterns = [
    url(r'^$', views.main_search, name="index"),
    url(r'^results/', views.search_results, name="results"),
    url(r'^compare/(?P<first_prop>[0-9]+)/(?P<second_prop>[0-9]+)/$',
        views.property_compare, name="compare"),
]

Aqarmap/listings/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

Aqarmap/listings/views.py
from django.shortcuts import render

from django.http import HttpRequest, HttpResponse, Http404
from django.shortcuts import redirect
from properties.models import Properties
from properties.forms import PropertiesForm
from django.core.paginator import   Paginator ,EmptyPage, PageNotAnInteger
from django.template import loader
from django.contrib.auth.decorators import login_required

import urlparse
from django import template
from django.conf import settings


# Create your views here.

@login_required
def listProperties(request):
    # template = loader.get_template('listProperties.html')

    p = Properties.objects.filter(owner_id=request.user.id)
    paginator = Paginator(p,5)

    page = request.GET.get('page')
    try:
        contacts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        contacts = paginator.page(1)
    except EmptyPage:
      # If page is out of range (e.g. 9999), deliver last page of results.
      contacts = paginator.page(paginator.num_pages)


    return render(request, 'listProperties.html', {'contacts': contacts})


    #context = {'p': p}

    #return render(request, "listProperties.html", context)




@login_required
def EditProp(request, prop_id):
    properties = Properties.objects.get(id=prop_id)
    if request.method == 'GET':
        form = PropertiesForm(instance=properties)
    else:
        form = PropertiesForm(request.POST, instance=properties)
        form.save()

        return redirect('listings:listProperties')
    context = {'form': form}

    return render(request, "editProperties.html", context)


@login_required
def delete(request, prop_id):

    property = Properties.objects.get(id=prop_id)
    property.delete()
    return redirect('listings:listProperties')

@login_required
def setActive(request, prop_id):
    property = Properties.objects.get(id=prop_id)
    property.status = True
    property.save()
    return redirect('listings:listProperties')


@login_required
def setDeactive(request, prop_id):
    property = Properties.objects.get(id=prop_id)
    property.status = False
    property.save()
    return redirect('listings:listProperties')

Aqarmap/listings/templates/editProperties.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
<div class="alert alert-info" role="alert">Edit my property</div>

<form method="POST" class="post-form form-horizontal" action="{{ request.get_full_path }}" enctype="multipart/form-data"
      role="form">

    {% csrf_token %}
    <!-- Property Description -->
    <div class="container">

        <h3><code>Property Description</code></h3>

        <div class="form-group">
            <label class="control-label col-sm-2" for="category">Category:</label>
            <div class="col-sm-10">
                {{ form.category }}
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-2" for="prop_type">Type:</label>
            <div class="col-sm-10">
                {{ form.prop_type }}
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-2" for="size">Size:</label>
            <div class="col-sm-10">
                {{ form.size }}
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-2" for="price">Price:</label>
            <div class="col-sm-10">
                {{ form.price }}
            </div>
        </div>
    </div>
    <!-- End Property Description -->

    <!-- Property Information -->
    <div class="container">
        <h3><code>Property Information</code></h3>

        <div class="form-group">
            <label class="control-label col-sm-2" for="title">Title:</label>
            <div class="col-sm-10">
                {{ form.title }}
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-2" for="description">Description:</label>
            <div class="col-sm-10">
                {{ form.description }}
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-2" for="city">City:</label>
            <div class="col-sm-10">
                {{ form.city }}
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-2" for="neighborhood">Neighborhood:</label>
            <div class="col-sm-10">
                {{ form.neighborhood }}
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-2" for="yt_url">YouTube Url (Optional) :</label>
            <div class="col-sm-10">
                {{ form.yt_url }}
            </div>
        </div>

    </div>
    <!-- End Property Information -->

    <!-- Marking position on the map -->
    <div class="container">
        <h3><code>Mark Your Property Location on the map</code></h3>
        <div class="form-group">
            <label class="control-label col-sm-2" for="position">Position:</label>
            <div class="col-sm-10">
                {{ form.media }}
                {{ form.position }}
                {{ form.position.latitude }}
                {{ form.position.longitude }}
            </div>
        </div>
    </div>
    <!-- End Marking position on the map -->


    <!-- Saving multiple photo -->
    <!-- 	<div class="container">
            <h3><code>Add your Photos</code></h3>

            <P><code>Add your Basic Photo</code></P>
            <div class="form-group">
                    <label class="control-label col-sm-2" for="position">Basic Photo:</label>
                    <div class="col-sm-10">
                    {{ form.basic_photo }}
                    </div>
            </div> -->


    <!--<div class="form-group">-->
        <!--<label class="control-label col-sm-2" for="position">Photos:</label>-->
        <!--<div class="col-sm-10">-->
            <!--{{ prop_form_set.as_p }}-->
        <!--</div>-->
    <!--</div>-->
    </div>
    <!-- EndSaving multiple photo -->


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="save btn btn-success">Save</button>
        </div>
    </div>
</form>

{% endblock %}

</body>
</html>

Aqarmap/listings/templates/listProperties.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
<div class="alert alert-info" role="alert">List my own properties</div> 
<table class="table table-bordered table-hover">
	<thead >
            <tr class="info">
                <th>Type </th>
                <th>Property name</th>
                <th>Announced date</th>
                <th>Status</th>
                <th>Action</th>
            </tr>
	</thead>
	<tbody>
		{% for a in contacts %}
			<tr>
				<td>{{a.prop_type}}</td>
				<td>{{a.title}}</td>
				<td>{{a.created}}</td>

				{% if a.status == 1 %}
					<td><a href="{% url 'listings:deactiveProperty' prop_id=a.id %}" ><button class="btn-danger btn"> Deactivate </button> </a></td>
				{% elif a.status == 0 %}
					<td><a href="{% url 'listings:activeProperty' prop_id=a.id %}" ><button class="btn-success btn"> Activate </button> </a></td>
				{% endif %}

				<td> <a href="{% url 'listings:editproperty' prop_id=a.id %}" ><button class="btn-success btn"> Edit </button> </a>
                     <a href="{% url 'listings:deleteProperty' prop_id=a.id %}" ><button class="btn-danger btn"> Delete </button> </a>

                </td>
			</tr>	
		
		{% endfor %}





	</tbody>


</table>

        <div class="pagination col-sm-12">
            <span class="step-links col-sm-offset-6">
                {% if contacts.has_previous %}
                    <a href="?page={{ contacts.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="current">
                        Page {{ contacts.number }} of {{ contacts.paginator.num_pages }}.
                    </span>
                    {% if contacts.has_next %}
                    <a href="?page={{ contacts.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>


{% endblock content %}