Aqarmap/Aqarmap/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin

from properties import urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^subscribtions/', include('subscribtions.urls', namespace='subscribtions')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^properties/', include('properties.urls', namespace='properties')),
    url(r'^listings/', include('listings.urls', namespace='listings')),
    url(r'^settings/', include('user_settings.urls', namespace='settings')),
    url(r'^', include('search.urls', namespace='search')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Aqarmap/properties/urls.py
from django.conf.urls import url
from . import views

app_name = 'properties'

urlpatterns = [
    url(r'^add/$', views.add_property, name='addproperty'),
    url(r'^forsale/$', views.prop_forSale, name='propertiesforsale'),
    url(r'^forrent/$', views.prop_forRent, name='propertiesforrent'),
    url(r'^all/$', views.list_u_prop, name='allproperties'),
    url(r'^(?P<property_id>[-0-9]+)/$',
        views.prop_details, name='properties_details'),
    # ex addProperty/5 - send <prop_id> as an arguments | [0-9]+ sequences of digits
    #url(r'^(?P<prop_id>[0-9]+)/$', views.details, name='prop_details'),
    #url(r'^(?P<addProperty_id>[0-9])/$', views.addProperty, name='add'),
]

Aqarmap/search/urls.py
from django.conf.urls import url

from . import views
app_name = 'search'
urlpatterns = [
    url(r'^$', views.main_search, name="index"),
    url(r'^results/', views.search_results, name="results"),
    url(r'^compare/(?P<first_prop>[0-9]+)/(?P<second_prop>[0-9]+)/$',
        views.property_compare, name="compare"),
]

Aqarmap/subscribtions/urls.py
from django.conf.urls import url
from . import views
app_name = 'subscribtions'
urlpatterns = [
	url(r'^$', views.subscribtions, name='subscribtions'),
	url(r'^add_subscribtion/', views.add_subscribtion, name='add_subscribtion'),
	url(r'^active/', views.active, name='active'),
	url(r'^delete_sub/', views.delete_sub, name='delete_sub'),
	url(r'^sub_results/', views.sub_results, name='sub_results'),
	]

Aqarmap/subscribtions/models.py
from __future__ import unicode_literals

from django.db import models
from accounts.models import UserProfile
from django.contrib.auth.models import User
from cities_light.models import City, Region
from properties.models import PROPERTIES_TYPES, PROPERTIES_CATEGORIES
# Create your models here.


class Subscribtions(models.Model):
    user = models.ForeignKey(UserProfile)
    city = models.ForeignKey(Region)  # need updating
    neighborhood = models.ForeignKey(City)  # need updating
    property_type = models.CharField(max_length=50, choices=PROPERTIES_TYPES)
    property_categories = models.CharField(
        max_length=1, choices=PROPERTIES_CATEGORIES)
    min_price = models.IntegerField()
    max_price = models.IntegerField()
    status = models.BooleanField(default=True)

Aqarmap/subscribtions/forms.py
from django import forms
from .models import Subscribtions
from properties.models import PROPERTIES_CATEGORIES, PROPERTIES_TYPES,STATUS
from cities_light.models import City, Region
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Field

class SubscribtionsForm(forms.Form):
	#then telling which model should be used to create this form
	city = forms.ModelChoiceField(queryset=Region.objects.all(), required=False)
	neighborhood = forms.ModelChoiceField(queryset=City.objects.all(), required=False)
	property_type = forms.ChoiceField(choices=PROPERTIES_TYPES, widget=forms.Select(), required=False)
	property_categories = forms.ChoiceField(choices=PROPERTIES_CATEGORIES, widget=forms.Select(), required=False)
	min_price = forms.IntegerField(min_value=0, required=False)
	max_price = forms.IntegerField(min_value=0, required=False)
	#status = forms.ChoiceField(STATUS,widget=forms.Select(),required=False)
	def __init__(self, *args, **kwargs):
		super(SubscribtionsForm, self).__init__(*args, **kwargs)
		self.helper = FormHelper()
		self.helper.form_id = 'subscribtions_form'
		self.helper.form_method = 'get'
		self.helper.form_action = 'add_subscribtion/'
		self.helper.form_class = 'form-inline'
		self.helper.field_template = 'bootstrap3/layout/inline_field.html'
		self.helper.layout = Layout(
			Field('city'),
            Field('neighborhood'),
            Field('property_type'),
            Field('property_categories'),
            Field('min_price'),
            Field('max_price'),
            #Field('status'),
        )
		self.helper.add_input(Submit('submit', 'Submit'))


    #def subscribtions(self, request, sub):
     #   sub.city = self.cleaned_data['city']
      #  sub.neighborhood = self.cleaned_data['neighborhood']
       # sub.property_type = self.cleaned_data['property_type']
       # sub.property_categories = self.cleaned_data['property_categories']
       # sub.min_price = self.cleaned_data['min_price']
        #sub.max_price = self.cleaned_data['max_price']
	#sub.status = self.cleaned_data['status']
     #   sub.save()

# class LoginForm(forms.ModelForm):
#     password = forms.CharField(widget=forms.PasswordInput())

#     def clean(self):
#         subname = self.cleaned_data.get('subname')
#         password = self.cleaned_data.get('password')
#         sub = authenticate(subname=subname, password=password)
#         if not sub:
#             raise forms.ValidationError("Sorry,")
#         return self.cleaned_data

#     class Meta:
#         model = sub
#         fields = ['subname', 'password']


# subCreationFormset = inlineformset_factory(
#     sub, subProfile, can_delete=False, exclude=['points', 'social_media',
#                                                   'messages', 'img_height', 'img_width'])

Aqarmap/subscribtions/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse, Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Subscribtions
from properties.models import Properties, PropertiesPhotos
from django.db.models import Q
from cities_light.models import City, Region
from subscribtions.forms import SubscribtionsForm
from django.template import loader
from django.contrib.auth.decorators import login_required

# def subscribtions(request):


@login_required
def subscribtions(request):

    form = SubscribtionsForm(request.POST or None)
    subs = Subscribtions.objects.all()
    context = {
        "form": form,
        "subs": subs,
    }
    return render(request, "subscribtion.html", context)


@login_required
def add_subscribtion(request):
    if request.method == "GET":
        # we will construct the form with it's data if it's a POST
        form = SubscribtionsForm(request.GET)

    # then check if the form is valid
        if form.is_valid():
            # process the data in the form.cleaned_data to return all the data
            # then accessing it
            values = form.cleaned_data
            #title = values['title']
            # cityId = values['city']
            # neighborhoodId = values['neighborhood']
            # cityObj = Region.objects.get(id=int(cityId))
            # neighborhoodObj = City.objects.get(id=int(neighborhoodId))

            sub = Subscribtions(property_type=values['property_type'], property_categories=values['property_categories'],
                                min_price=values[
                                    'min_price'], max_price=values['max_price'],
                                city=values['city'], neighborhood=values['neighborhood'], user=request.user)
            #subscribtions = form.save(commit=False)
            sub.save()
            return redirect('subscribtions:subscribtions')
    else:
        form = SubscribtionsForm()
    template = loader.get_template('subscribtion.html')
    context = {'form': form, }
    return HttpResponse(template.render(context, request))


@login_required
def active(request):
    sub_id = request.GET.get("sub_id")
    sub = Subscribtions.objects.get(pk=sub_id)
    if sub.status == False:
        sub.status = True
        sub.save()
    else:
        sub.status = False
        sub.save()
    return redirect('subscribtions:subscribtions')


@login_required
def delete_sub(request):
    sub_id = request.GET.get("sub_id")
    sub = Subscribtions.objects.get(pk=sub_id).delete()
    return redirect('subscribtions:subscribtions')


@login_required
def sub_results(request):
    sub = Subscribtions.objects.filter(user_id=request.user)
    subs = []
    for subscribtion in sub:
        props = Properties.objects.filter(city=subscribtion.city,neighborhood=subscribtion.neighborhood,category=subscribtion.property_categories,prop_type=subscribtion.property_type,price__range=(subscribtion.min_price,subscribtion.max_price))
        properties = PropertiesPhotos.objects.filter(prop__in=props).select_related('prop')
      #if properties in subs:
       # continue
        #else:
        subs.append(properties)
    paginator = Paginator(subs, 1)
    page = request.GET.get('page')
    try:
        props = paginator.page(page)
    except PageNotAnInteger:
        props = paginator.page(1)
    except EmptyPage:
        props = paginator.page(paginator.num_pages)
    template = loader.get_template('results.html')
    context = {'subs':props,}
    #print(subs[0].values('id'))
    return HttpResponse(template.render(context, request))

Aqarmap/subscribtions/templates/results.html
{% extends "base.html" %} {% load humanize %} {% load staticfiles %}
{% block js %}
    <script src='{% static "search/js/results-utils.js" %}'></script>
{% endblock js %}
{% block content %}
<div class="row">
    <h1>Search Results</h1>
    <hr> {% for result in subs %}
    	{% for subResult in result %}
    <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
        <div class="thumbnail">
            <img src="{{ subResult.prop_photo.url }}" alt="">
            <div class="caption">
                <h2>{{ subResult.prop.title }} | <small>{{ subResult.prop.created|naturaltime }}</small></h2>
                <small>Type : {{ subResult.prop.prop_type }}</small> | <small> Size : {{ subResult.prop.size }}<small> M</small> | Price : {{ subResult.prop.price|intcomma }}<small> EGP</small></small>
                <hr>
                <div class="well well-sm">
                    <p>
                        {{ subResult.prop.description | truncatechars:100}}
                    </p>
                </div>
                <div>
                    <p>
                        <a href="{% url 'properties:properties_details' property_id=subResult.id %}" class="btn btn-primary">Detail</a>
                    </p>
                </div>

            </div>
        </div>
    </div>
    {% endfor %}
    {% endfor %}


</div>
<div class="pagination">
    <span class="step-links">
        {% if subs.has_previous %}
            <a href="?page={{ subs.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ subs.number }} of {{ subs.paginator.num_pages }}.
        </span>

        {% if subs.has_next %}
            <a href="?page={{ subs.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>
{% endblock content %}

Aqarmap/subscribtions/templates/subscribtion.html
{% extends "base.html" %} {% load crispy_forms_tags %} 




<div class="row">
{% block content %}

<h1>Subscribtions</h1>
    <hr>
    <table class="table table-bordered table-hover"><tr><td>{% crispy form %}</td></tr>
    </table>

	<hr>
    {% if subs %}
        
    <div class="row">
    <h1>Your Subscribtions</h1>
    <table class="table table-bordered table-hover">
    <tr>
    <th>City</th><th>Neightborhood</th><th>Property Type</th><th>Property Category</th><th>Min Price</th><th>Max Price</th><th>Status</th><th>Delete</th></tr>
    {% for value in subs %}
    <tr>
    <td><span>{{value.city}}</span></td>
    <td><span>{{value.neighborhood}}</span></td>
    <td><span>{{value.property_type}}</span></td>
    <td><span>{{value.property_categories}}</span></td>
    <td><span>{{value.min_price}}</span></td>
    <td><span>{{value.max_price}}</span></td>
    <td>{% if value.status %}<a href="{% url 'subscribtions:active' %}?sub_id={{ value.id }}" class="btn btn-success">Active</a>
    {% else %}
    <a href="{% url 'subscribtions:active' %}?sub_id={{ value.id }}" class="btn btn-danger">InActive</a>
    {% endif %}
    </td>
    <td><a href="{% url 'subscribtions:delete_sub' %}?sub_id={{ value.id }}" class="btn btn-danger">Delete</a></td>
    </tr>
        {% endfor %}
    </table>
</div>

    {% endif %}
{% endblock content %}
</div>