Aqarmap/Aqarmap/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin

from properties import urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^subscribtions/', include('subscribtions.urls', namespace='subscribtions')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^properties/', include('properties.urls', namespace='properties')),
    url(r'^listings/', include('listings.urls', namespace='listings')),
    url(r'^settings/', include('user_settings.urls', namespace='settings')),
    url(r'^', include('search.urls', namespace='search')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Aqarmap/listings/urls.py
from django.conf.urls import url
from . import views

app_name = 'listing'

urlpatterns = [

    url(r'^listProperties/$', views.listProperties, name='listProperties'),
    url(r'^editProperties/(?P<prop_id>[0-9]+)/$', views.EditProp, name='editproperty'),
    url(r'^deleteProperties/(?P<prop_id>[0-9]+)/$', views.delete, name='deleteProperty'),
    url(r'^activateProperties/(?P<prop_id>[0-9]+)/$', views.setActive, name='activeProperty'),
    url(r'^deactivateProperties/(?P<prop_id>[0-9]+)/$', views.setDeactive, name='deactiveProperty')

]

Aqarmap/properties/urls.py
from django.conf.urls import url
from . import views

app_name = 'properties'

urlpatterns = [
    url(r'^add/$', views.add_property, name='addproperty'),
    url(r'^forsale/$', views.prop_forSale, name='propertiesforsale'),
    url(r'^forrent/$', views.prop_forRent, name='propertiesforrent'),
    url(r'^all/$', views.list_u_prop, name='allproperties'),
    url(r'^(?P<property_id>[-0-9]+)/$',
        views.prop_details, name='properties_details'),
    # ex addProperty/5 - send <prop_id> as an arguments | [0-9]+ sequences of digits
    #url(r'^(?P<prop_id>[0-9]+)/$', views.details, name='prop_details'),
    #url(r'^(?P<addProperty_id>[0-9])/$', views.addProperty, name='add'),
]

Aqarmap/search/urls.py
from django.conf.urls import url

from . import views
app_name = 'search'
urlpatterns = [
    url(r'^$', views.main_search, name="index"),
    url(r'^results/', views.search_results, name="results"),
    url(r'^compare/(?P<first_prop>[0-9]+)/(?P<second_prop>[0-9]+)/$',
        views.property_compare, name="compare"),
]

Aqarmap/subscribtions/urls.py
from django.conf.urls import url
from . import views
app_name = 'subscribtions'
urlpatterns = [
	url(r'^$', views.subscribtions, name='subscribtions'),
	url(r'^add_subscribtion/', views.add_subscribtion, name='add_subscribtion'),
	url(r'^active/', views.active, name='active'),
	url(r'^delete_sub/', views.delete_sub, name='delete_sub'),
	url(r'^sub_results/', views.sub_results, name='sub_results'),
	]

Aqarmap/user_settings/urls.py
from django.conf.urls import url, include
from . import views
urlpatterns = [
    url(r'^$', views.user_setting, name='user_setting'),
]

Aqarmap/templates/base.html
<!DOCTYPE html>
<html>

<head>
    {% load staticfiles %}
    <title>{% block head_title %} Aqarmap {% endblock head_title %} </title>
    <style type="text/css">
    html,
    body {
        margin: 0;
        padding: 0;
        height: 100%;
    }
    
    #container {
        min-height: 100%;
        position: relative;
    }
    
    #body {
        padding: 10px;
        padding-bottom: 60px;
        /* Height of the footer */
    }
    
    #footer {
        position: relative;
        bottom: 0;
        width: 100%;
        height: 60px;
        /* Height of the footer */
        background: #6cf;
    }
    </style>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    {% block js %} {% endblock js %}
</head>

<body bgcolor="#25383C">
    <div id="container">
        <div id="header">
            <!-- Header -->
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <a class="navbar-brand" href="{% url 'search:index' %}">AQAR MAP ITI</a>
                    </div>
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'search:index' %}">Home</a></li>
                        {% if request.user.is_authenticated %}
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Property
                                        <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'properties:allproperties' %}">List All Properties</a></li>
                                <li><a href="{% url 'properties:propertiesforsale' %}">Properties for sale</a></li>
                                <li><a href="{% url 'properties:propertiesforrent' %}">Properties for rent</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Projects
                                        <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Add Project</a></li>
                                <li><a href="#">List Projects</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Listings
                                        <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'properties:addproperty' %}">Add Property</a></li>
                                <li><a href="{% url 'listings:listProperties' %}">My Listings</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Subscribtions
                                        <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'subscribtions:sub_results' %}">Feeds</a></li>
                                <li><a href="{% url 'subscribtions:subscribtions' %}">Add Subscribtion</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Settings
                                        <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'settings:user_setting' %}">Edit Profile</a></li>
                                <li><a href="{% url 'account_change_password' %}">Change Password</a></li>
                                <li><a href="{% url 'account_email' %}">Edit Emails</a></li>
                            </ul>
                        </li>
                        {% endif %}
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Search Box -->
                        <!-- Endo Of search -->
                        {% if request.user.is_authenticated %}
                        <li><a href="{% url 'account_logout' %}"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
                        {% else %}
                        <li><a href="{% url 'account_signup' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                        <li><a href="{% url 'account_login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </div>
        <!-- Header Navvvvvvv -->
        <!-- Body -->
        <div id="body">
            <div class="container">
                {% block content %} {% endblock content %}
            </div>
        </div>
        <!-- End of body -->
        <!-- Footer -->
        <div id="footer">
            <footer>
                <nav class="navbar navbar-default">
                    <h1 align="center">AQAR MAP ITI</h1>
                    <p align="center">Contact information: aqarmapiti@ymail.com</p>
                </nav>
            </footer>
        </div>
        <!-- End of Footer -->
    </div>
</body>

</html>